In [16]:
import pandas as pd
import openpyxl

In [21]:
shark_attack = pd.read_csv(r"D:\\ironhack\\proyecto\\proy_1\\attacks.csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 721: invalid start byte

In [19]:
attacks = pd.read_excel(r'D:\\ironhack\\proyecto\\proy_1\\attackss.xlsx', engine="openpyxl")

In [20]:
attacks

,"Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex ,Age,Injury,Fatal (Y/N),Time,Species ,Investigator or Source,pdf,href formula,href,Case Number,Case Number,original order,,",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,"2018.06.25,25-Jun-2018,2018,Boating,USA,Califo...",NaN,NaN,NaN,NaN,NaN,NaN
1,"2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Geo...",NaN,NaN,NaN,NaN,NaN,NaN
2,"2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii...",NaN,NaN,NaN,NaN,NaN,NaN
3,"2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRAL...",NaN,NaN,NaN,NaN,NaN,NaN
4,"2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Co...",NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
25711,",,,,,,,,,,,,,,,,,,,,,,,",NaN,NaN,NaN,NaN,NaN,NaN
25712,",,,,,,,,,,,,,,,,,,,,,,,",NaN,NaN,NaN,NaN,NaN,NaN
25713,",,,,,,,,,,,,,,,,,,,,,,,",NaN,NaN,NaN,NaN,NaN,NaN
25714,",,,,,,,,,,,,,,,,,,,,,,,",NaN,NaN,NaN,NaN,NaN,NaN
25715,"xx,,,,,,,,,,,,,,,,,,,,,,,",NaN,NaN,NaN,NaN,NaN,NaN